
  spring.jpa.database=INFORMIX
  spring.sql.init.platform=informix
  spring.jpa.show-sql=true
  spring.jpa.hibernate.ddl-auto=update
  spring.database.driverClassName=com.informix.jdbc.IfxDriver
  spring.datasource.url=jdbc:jdbc:informix-sqli://192.168.15.30:9088/sescsp:INFORMIXSERVER=ol_database
  spring.datasource.username=informix
  spring.datasource.password=I1n2f3o4
  server.port=8080