server:
    port: 8080
datasource:
    driver-class-name: com.informix.jdbc.IfxDriver
    url: jdbc:informix-sqli://192.168.15.30:9088/sescsp:INFORMIXSERVER=ol_database
    username: informix
    password: I1n2f3o4